<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_DigitalOutputSoftware" Id="{04c3a81b-05a4-4c3a-bc05-1f5bded7fe93}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DigitalOutputSoftware EXTENDS FB_DigitalOutputBase
VAR
	HardwareOutput AT %Q* : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>