<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{992a4bb5-a518-488f-ae00-ab35077fe46f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbEquipmentModule : FB_EquipmentModule;
	fbVisu : FB_Visu();
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbEquipmentModule.Run();

fbVisu(fbEquipmentModule := fbEquipmentModule);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>