<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{5a08b74e-1f52-4672-a78b-c5cf190f2641}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbMotorTest  : FB_Motor_Test;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN_IN_SEQUENCE();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>